server:
  port: 9090
  error:
    whitelabel:
      enabled: false

api:
  facebook:
    graphUri: https://graph.facebook.com/v3.2/

spring:
  h2:
    console.enabled: true
  session:
    timeout:
      seconds: 900
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/schemaevolver
    username: root
    password: root-password
    driver-class-name: com.mysql.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 241969880427134
            clientSecret: 8b3a89ec0d35df33f5d5b8991ad76b50
#            scope: profile email
          github:
            clientId: dc72c807f44a0e42e579
            clientSecret: abcdb14421313d4b52d90774d9f550b786d91279
          google:
            clientId: 335730775851-3m7naio5s8075fsbnd97n14v4famufjr.apps.googleusercontent.com
            clientSecret: 1RBSb771wxwOZjyorukOOL5e

file:
#  upload-dir: /Users/callicoder/uploads
